### ISSUE TITLE
Make ping-pong lower level

### ISSUE THREAD

**Issue by mcollina** [jasonkuhrt-archive/ping-pong#1]
It seems ping/pong is using the 'data' event directly, which put the stream in 'old mode'. 

I think we should develop a "ping-pong" util that is unaware of the underlining protocol/data format, so we can test it better.

Something along the line:

``` javascript
function doPing() {
  // send a ping!
}

var interval = 5000;
var retries = 3;

var pingPong = new PingPong(interval, retries, doPing);

// call this any time a 'pong' is received, or there was some
// activity that reset the PingPong timer.
pingPong.catchPong();

pingPong.on("pongMissed", function(number) {
  console.log("a pong was missed", number);
});

pingPong.on("error", function(err) {
  // err will be 'maximum retries reached'
  console.log("an error occurred", err);
});
```

**Comment by jasonkuhrt** [comment]
Yep totally makes sense. As we agreed on the call this library can just provide the bare minimum timer logic (a worthwhile and valiant contribution) with function hooks for defining what `ping` and `catchPong` really mean to the _user_.

**Comment by jasonkuhrt** [comment]
@mcollina I tried to keep things pretty sparse. I haven't included support for an `eventEmitter` at this time either, intend the constructor just takes `ping` and `onTimeout` functions.

**Comment by mcollina** [comment]
Cool. Events are better only if you need multiple listeners, while functions are faster. I think in this case it's almost equal.
